#!/bin/bash 

#SBATCH -A FY190020
#SBATCH -t 03:59:00
#SBATCH -o machine.out
#SBATCH -J test1
#SBATCH -N 32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kevmoor@sandia.gov

source attaway_setup_env.sh

nodes=$SLURM_JOB_NUM_NODES
rpn=$(ranks_per_node)
ranks=$(( $rpn*$nodes ))

srun -N $nodes -n $ranks naluX -i a.yaml -o test1.out &> log


